config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :past_reservations
    end
  end
  
  resources :reservations,  except: [:new]
  resources :calendars,  only: [:index, :show]
  resources :members, except: [:show]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :calendar
  has_many :members, dependent: :destroy
  accepts_nested_attributes_for :members
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  def index
    @reservations = Reservation.all.order("date ASC").page(params[:page])
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    if  Reservation.where(calendar_id: target_calendar.id).any?
      flash[:danger] = 'すでに予約されています'
      render 'toppages/index'
    else
      @reservation = target_calendar.build_reservation(reservation_params)
      
      if @reservation.save
        @reservation.members.create(name: current_user.name, leader: 1)
        flash[:success] = '予約を確定しました。続いて参加者を登録してください。'
        get_reservation(@reservation)
        session[:double_booking] = '1'
        redirect_to controller: 'members', action: 'new'
      
      else
        flash[:danger] = '予約できませんでした'
        redirect_to controller: 'calendars', action: 'index'
      end
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    unless current_user.id == @reservation.user_id
      redirect_to current_user
    else
      d = Date.today
      today = d.strftime("%Y%m%d").to_i
      if @reservation.date < today
        redirect_to current_user
      end
    end  
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:success] = '予約を変更しました'
      redirect_to @reservation
    else
      flash.now[:danger] = '予約の変更はできませんでした。'
      render :edit
    end
  end

  def destroy
    @reservation.destroy
    flash[:success] = '予約をキャンセルしました。'
    redirect_to controller: 'toppages', action: 'index'
  end
  
  private  

  def reservation_params
    params.require(:reservation).permit(:date,:place,:course,:remarks,:user_id)
  end
  
  def correct_user
    @reservation = current_user.reservations.find_by(id: params[:id])
    unless @reservation
      redirect_to root_url
    end
  end
    
  def get_reservation(reservation)
    session[:reservation_id] = reservation.id
  end  
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def target_reservation
    @target_reservation ||= Reservation.find_by(id: session[:reservation_id])
  end
end

app/views/reservations/_past_reservations.html.erb
<ul class="list-unstyled">
<% d = Date.today %>
<% today = d.strftime("%Y%m%d").to_i %>
<% if reservations.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>詳細</th>
        <th>開催日</th>
        <th>コース</th>
      </tr>
    </thead>
    <tbody>
      <% reservations.each do |reservation| %>
        <% if reservation.date < today %>
          <tr>
            <td><%= link_to '【詳細確認】', reservation_path(reservation) %></td>
            <td><%= reservation.date.to_s.to_date.strftime("%Y年%m月%d日") %></td>
            <td><%= reservation.course %></td>
          </tr>
        <% else %>
          <% next %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate reservations %>
  </div>
<% end %>

app/views/reservations/_reservations.html.erb
<ul class="list-unstyled">
<% d = Date.today %>
<% today = d.strftime("%Y%m%d").to_i %>
<% if reservations.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>処理</th>
        <th>開催日</th>
        <th>コース</th>
      </tr>
    </thead>
    <tbody>
      <% reservations.each do |reservation| %>
        <% if reservation.date >= today %>
          <tr>
            <td><%= link_to '【変更・キャンセル】', edit_reservation_path(reservation) %></td>
            <td><%= reservation.date.to_s.to_date.strftime("%Y年%m月%d日") %></td>
            <td><%= reservation.course %></td>
          </tr>
        <% else %>
          <% next %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate reservations %>
  </div>
<% end %>

app/views/reservations/cancel.html.erb
<div class="text-center">
  <h1>予約のキャンセル</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @reservation, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :course, 'コース   　　　 ' %>
        <%= @reservation.course %>
        <%= f.hidden_field :course, :value =>'' %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '日付    　　　　' %>
        <%= @reservation.date.to_s.to_date.strftime("%Y年%m月%d日") %>
      </div>

      <div class="form-group">
        <%= f.label :place, '研修室   　　　 ' %>
        <%= @reservation.place %>
      </div>
      
    　<div class="form-group">
        <%= f.label :remarks, '備考    　　　　' %>
        <%= @reservation.remarks %>
        <%= f.hidden_field :remarks, :value =>'' %>
      </div>
      
      <%= f.hidden_field :user, :value =>'' %>
      <p>以上の内容をキャンセルしますか？</p>
      <%= f.submit 'キャンセルする', class: 'btn btn-primary btn-block' %>
      
    <% end %>
  </div>
</div>

<div class="text-center">
<%= link_to 'カレンダーに戻る', reservations_path %>
</div>

app/views/reservations/edit.html.erb
<div class="text-center">
  <h1>予約の変更</h1>
</div>

<div class="row">
  <aside class="col-sm-2">
    <%= link_to raw("参加者を<br/>確認・変更する"), members_path(@reservation.id), class: 'btn btn-success btn-block'%>
    <%# if current_user.id == @reservation.user_id %>
    <%= link_to "予約のキャンセル", @reservation, method: :delete, data: { confirm: "予約をキャンセルしますか?" }, class: 'btn btn-danger btn-block' %>
  </aside>
  
  <div class="col-sm-10">
    <%= form_with(model: @reservation, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :course, 'コース   　　　 ' %>
        <%#= select_tag :course, options_for_select(['新人研修',' 管理職研修', '現場責任者研修','上級管理職研修'], @reservation.course), include_blank: true %>
        <%= f.collection_select :course, Course.all, :name, :name, {include_blank: true,selected:@reservation.course} %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '日付    　　　　' %>
        <%= @reservation.date.to_s.to_date.strftime("%Y年%m月%d日") %>
      </div>

      <div class="form-group">
        <%= f.label :place, '会場    　　　　' %>
        <%= @reservation.place %>
      </div>
      
    　<div class="form-group">
        <%= f.label :remarks, '備考(２５０文字）' %>
        <%= f.text_area :remarks, value:@reservation.remarks, class: 'form-control' ,rows: 5  %>
      </div>
      <%= f.hidden_field :user, :value =>current_user.id %>
      
      <div class = "text-center" >
        <%= f.submit '変更する', class: 'btn btn-primary btn-sm' %>
        <p><a> <%= link_to 'ユーザページに戻る',user_path(current_user) %> </a></p>
      </div>
      
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="text-center">
  <h1>研修予約</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @reservation, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :course, 'コース' %>
        <%= f.text_field :course, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '日付    　　　　' %>
        <%= date = @date%>
        <%= date.to_s.to_date.strftime("%Y年%m月%d日") %>
      </div>

      <div class="form-group">
        <%= f.label :place, '会場    　　　　' %>
        <%= place = params[:calendar_place]%>
        <a> place </a>
        <%= @place %>
      </div>
      
    　<div class="form-group">
        <%= f.label :remarks, '備考(２５０文字）' %>
        <%= f.text_area :remarks, class: 'form-control' ,rows: 5  %>
      </div>
      
      <%= f.submit '予約する', class: 'btn btn-primary btn-block' %>
      
      
    <% end %>
  </div>
</div>

<div class="text-center">
<%= link_to 'カレンダーに戻る', reservations_path %>
</div>

app/views/reservations/show.html.erb
<div class="text-center">
  <h1>予約詳細</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @reservation, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :course, 'コース   　　　 ' %>
        <%= @reservation.course %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '日付    　　　　' %>
        <%= @reservation.date.to_s.to_date.strftime("%Y年%m月%d日") %>
      </div>

      <div class="form-group">
        <%= f.label :place, '研修室   　　　 ' %>
        <%= @reservation.place %>
      </div>
      
    　<div class="form-group">
        <%= f.label :remarks, '備考(２５０文字）' %>
        <%= f.text_area :remarks, class: 'form-control' ,rows: 5  %>
      </div>
      
    <% end %>
  </div>
</div>

<div class="text-center">
<%= link_to 'カレンダーに戻る', reservations_path %>
</div>