config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :past_reservations
    end
  end
  
  resources :reservations,  except: [:new]
  resources :calendars,  only: [:index, :show]
  resources :members, except: [:show]
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_one  :reservation
  has_one  :user, through: :reservations
  
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :require_user_logged_in
  def index
    default_date = 0
    @date = params[:date].to_i || default_date
    @date2 = @date + 30
    default_place = 0
    @place = params[:place] || default_place
    @calendars = Calendar.where(date: @date..@date2, place: @place).page(params[:page])

  end

  def show
    get_calendar
    @reservation = target_calendar.build_reservation
    @date = Calendar.find(params[:id]).date
    @place = Calendar.find(params[:id]).place
  end

  private
  
  def get_calendar
    @calendar = Calendar.find(params[:id])
    session[:calendar_id] = @calendar.id
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def target_calendar
    @target_calendar ||= Calendar.find_by(id: session[:calendar_id])
  end
end

app/views/calendars/_reserve_button.html.erb
<% if calendar.reservation %>
  <td><a href="#" class="btn btn-danger">予約不可</a></td>
<% else %>
  <td><%= link_to '予約する', calendar_path(calendar),  class: "btn btn-primary" %></td>
<% end %>

app/views/calendars/index.html.erb
<ul class="list-unstyled">
<% d = Date.today %>
<% today = d.strftime("%Y%m%d").to_i %>
<%= form_tag calendars_path, method: :get do %>
  <span>年月選択: <%= select_tag 'date', options_for_select({２０２０年４月: 20200401, ２０２０年５月: 20200501, ２０２０年６月: 20200601,２０２０年７月: 20200701}, @date), include_blank: true %></span>
  <span>会場選択: <%= select_tag 'place', options_for_select(['大研修場','中研修場', '小研修場１','小研修場２'], @place), include_blank: true %></span>
  <%= button_to "表示する", {controller: 'calendars', action: 'index'}, {method: :get} %>
<% end %>

<% if @calendars.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>予約</th>
        <th>年月日</th>
      </tr>
    </thead>
    <tbody>
      <% @calendars.each do |calendar| %>
        <% if calendar.date >= today %>
          <tr>
            <%= render 'calendars/reserve_button',calendar:calendar %>
            <td><%= calendar.date.to_s.to_date.strftime("%Y年%m月%d日") %></td>
          </tr>
        <% else %>
          <% next %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @calendars %>
  </div>
<% end %>

app/views/calendars/show.html.erb
<% if logged_in? %>
  <div class="text-center">
    <h1>研修予約</h1>
  </div>
  
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
  
      <%= form_with(model: @reservation, local: true) do |f| %>
      
        <div class="form-group">
          <%= f.label :course, 'コース   　　　 ' %>
          <%= f.collection_select :course, Course.all, :name, :name, include_blank: true %>
        </div>
        
        <div class="form-group">
          <%= f.label :date, '日付    　　　　' %>
          <%= @date.to_s.to_date.strftime("%Y年%m月%d日") %>
          <%= f.hidden_field :date, :value =>@date %>
        </div>
  
        <div class="form-group">
          <%= f.label :place, '研修場   　　　 ' %>
          <%= @place %>
          <%= f.hidden_field :place, :value =>@place %>
        </div>
        
      　<div class="form-group">
          <%= f.label :remarks, '備考(２５０文字）' %>
          <%= f.text_area :remarks, class: 'form-control' ,rows: 5  %>
        </div>
        
        <%= f.hidden_field :user_id, :value =>current_user.id %>
        
        <%= f.submit '予約する', class: 'btn btn-primary btn-block' %>
        
      <% end %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>